
#import "YFConst.h"

NSString *const ANOTI = @"ANOTI";

NSString *const SEARCHHISFILE = @"searchHistory.plist";

NSString *const GUIDENOTI = @"GUIDE2MAINNOTI";

NSString *const HOMESCROLLIDEN=@"HOMESCROLLIDEN";
NSString *const GETRECLISTNOTI=@"GETRECLISTNOTI";
NSString *const ON_BIDDING_CHANGE_NOTI=@"ON_BIDDING_CHANGE_NOTI";
NSString *const ON_BIDDING_SETTING_CHANGE=@"ON_BIDDING_SETTING_CHANGE";



#ifdef DEBUG
NSString *const APPSTORE_APPID=@"414478124";
NSString *const APP_IDENNAME=@"BATTERY_CAM";
#else
NSString *const APPSTORE_APPID=@"414478124";
NSString *const APP_IDENNAME=@"BATTERY_CAM";
#endif
